/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldForecastRouteImport } from './routes/yield-forecast'
import { Route as WaterAdvisoryRouteImport } from './routes/water-advisory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MoistureStressRouteImport } from './routes/moisture-stress'
import { Route as IrrigationRouteImport } from './routes/irrigation'
import { Route as GrowthStagesRouteImport } from './routes/growth-stages'
import { Route as FieldMapRouteImport } from './routes/field-map'
import { Route as CropClassificationRouteImport } from './routes/crop-classification'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const YieldForecastRoute = YieldForecastRouteImport.update({
  id: '/yield-forecast',
  path: '/yield-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterAdvisoryRoute = WaterAdvisoryRouteImport.update({
  id: '/water-advisory',
  path: '/water-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoistureStressRoute = MoistureStressRouteImport.update({
  id: '/moisture-stress',
  path: '/moisture-stress',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationRoute = IrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthStagesRoute = GrowthStagesRouteImport.update({
  id: '/growth-stages',
  path: '/growth-stages',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldMapRoute = FieldMapRouteImport.update({
  id: '/field-map',
  path: '/field-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CropClassificationRoute = CropClassificationRouteImport.update({
  id: '/crop-classification',
  path: '/crop-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/crop-classification': typeof CropClassificationRoute
  '/field-map': typeof FieldMapRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/irrigation': typeof IrrigationRoute
  '/moisture-stress': typeof MoistureStressRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-advisory': typeof WaterAdvisoryRoute
  '/yield-forecast': typeof YieldForecastRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/crop-classification': typeof CropClassificationRoute
  '/field-map': typeof FieldMapRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/irrigation': typeof IrrigationRoute
  '/moisture-stress': typeof MoistureStressRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-advisory': typeof WaterAdvisoryRoute
  '/yield-forecast': typeof YieldForecastRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof ChatbotRoute
  '/crop-classification': typeof CropClassificationRoute
  '/field-map': typeof FieldMapRoute
  '/growth-stages': typeof GrowthStagesRoute
  '/irrigation': typeof IrrigationRoute
  '/moisture-stress': typeof MoistureStressRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-advisory': typeof WaterAdvisoryRoute
  '/yield-forecast': typeof YieldForecastRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/chatbot'
    | '/crop-classification'
    | '/field-map'
    | '/growth-stages'
    | '/irrigation'
    | '/moisture-stress'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/water-advisory'
    | '/yield-forecast'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/chatbot'
    | '/crop-classification'
    | '/field-map'
    | '/growth-stages'
    | '/irrigation'
    | '/moisture-stress'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/water-advisory'
    | '/yield-forecast'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/chatbot'
    | '/crop-classification'
    | '/field-map'
    | '/growth-stages'
    | '/irrigation'
    | '/moisture-stress'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/water-advisory'
    | '/yield-forecast'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ChatbotRoute: typeof ChatbotRoute
  CropClassificationRoute: typeof CropClassificationRoute
  FieldMapRoute: typeof FieldMapRoute
  GrowthStagesRoute: typeof GrowthStagesRoute
  IrrigationRoute: typeof IrrigationRoute
  MoistureStressRoute: typeof MoistureStressRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WaterAdvisoryRoute: typeof WaterAdvisoryRoute
  YieldForecastRoute: typeof YieldForecastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-forecast': {
      id: '/yield-forecast'
      path: '/yield-forecast'
      fullPath: '/yield-forecast'
      preLoaderRoute: typeof YieldForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-advisory': {
      id: '/water-advisory'
      path: '/water-advisory'
      fullPath: '/water-advisory'
      preLoaderRoute: typeof WaterAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moisture-stress': {
      id: '/moisture-stress'
      path: '/moisture-stress'
      fullPath: '/moisture-stress'
      preLoaderRoute: typeof MoistureStressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation': {
      id: '/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof IrrigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-stages': {
      id: '/growth-stages'
      path: '/growth-stages'
      fullPath: '/growth-stages'
      preLoaderRoute: typeof GrowthStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-map': {
      id: '/field-map'
      path: '/field-map'
      fullPath: '/field-map'
      preLoaderRoute: typeof FieldMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-classification': {
      id: '/crop-classification'
      path: '/crop-classification'
      fullPath: '/crop-classification'
      preLoaderRoute: typeof CropClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ChatbotRoute: ChatbotRoute,
  CropClassificationRoute: CropClassificationRoute,
  FieldMapRoute: FieldMapRoute,
  GrowthStagesRoute: GrowthStagesRoute,
  IrrigationRoute: IrrigationRoute,
  MoistureStressRoute: MoistureStressRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WaterAdvisoryRoute: WaterAdvisoryRoute,
  YieldForecastRoute: YieldForecastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
